"""Integration tests for the AEGIS API: read endpoints, and the guarded
approval/execution safety gates (fail-closed + idempotent behavior).
"""

import pytest
from fastapi.testclient import TestClient

from api.main import app

client = TestClient(app)

INCIDENT_ID = "INC-20260930-001"


def test_health():
    response = client.get("/health")
    assert response.status_code == 200
    body = response.json()
    assert body["status"] == "healthy"
    assert body["production_execution_enabled"] is False


def test_list_incidents():
    response = client.get("/api/incidents")
    assert response.status_code == 200
    body = response.json()
    assert body["incident_count"] >= 1
    assert any(i["incident_id"] == INCIDENT_ID for i in body["incidents"])


def test_get_incident_ok():
    response = client.get(f"/api/incidents/{INCIDENT_ID}")
    assert response.status_code == 200
    assert response.json()["incident_id"] == INCIDENT_ID


def test_get_incident_not_found():
    response = client.get("/api/incidents/INC-20990101-999")
    assert response.status_code == 404


@pytest.mark.parametrize(
    "bad_id",
    ["not-a-real-id", "'; DROP TABLE incidents;--", "INC-2026-01"],
)
def test_get_incident_rejects_malformed_id(bad_id):
    response = client.get(f"/api/incidents/{bad_id}")
    assert response.status_code == 400


@pytest.mark.parametrize(
    "endpoint",
    ["risk", "strategies", "decision", "explanation", "impact", "verification", "audit"],
)
def test_read_endpoints_ok(endpoint):
    response = client.get(f"/api/incidents/{INCIDENT_ID}/{endpoint}")
    assert response.status_code == 200


def test_prevention_endpoint_ok():
    # Prevention artifact is generated by engine.prevention.prevention_engine;
    # skip gracefully if it has never been run in this environment.
    response = client.get(f"/api/incidents/{INCIDENT_ID}/prevention")
    assert response.status_code in (200, 404)


def test_agent_investigation_stops_before_human_approval(monkeypatch):
    class FakeOrchestrator:
        def run_analysis(self, incident_id):
            return {
                "incident_id": incident_id,
                "workflow_status": "WAITING_FOR_HUMAN_APPROVAL",
                "execution_allowed": False,
                "production_execution_allowed": False,
                "investigation": {"status": "COMPLETED"},
                "recovery_analysis": {
                    "details": {"recommended_strategy": {"strategy_id": "REC-002"}}
                },
            }

    monkeypatch.setattr("api.main.RecoveryOrchestratorAgent", FakeOrchestrator)
    response = client.post(f"/api/incidents/{INCIDENT_ID}/investigate")
    assert response.status_code == 200

    body = response.json()
    assert body["workflow_status"] == "WAITING_FOR_HUMAN_APPROVAL"
    assert body["execution_allowed"] is False
    assert body["production_execution_allowed"] is False
    assert body["investigation"]["status"] == "COMPLETED"
    assert body["recovery_analysis"]["details"]["recommended_strategy"]["strategy_id"] == "REC-002"


def test_agent_report_endpoint_returns_persisted_analysis(monkeypatch):
    monkeypatch.setattr(
        "api.main.load_agent_report",
        lambda incident_id: {
            "incident_id": incident_id,
            "orchestrator": "recovery_orchestrator",
        },
    )
    response = client.get(f"/api/incidents/{INCIDENT_ID}/agents")
    assert response.status_code == 200
    assert response.json()["orchestrator"] == "recovery_orchestrator"


def test_verified_prevention_agent_endpoint(monkeypatch):
    class FakeOrchestrator:
        def run_post_recovery(self, incident_id):
            return {
                "incident_id": incident_id,
                "workflow_status": "COMPLETED",
                "execution_allowed": False,
                "prevention_analysis": {"status": "COMPLETED"},
            }

    monkeypatch.setattr("api.main.RecoveryOrchestratorAgent", FakeOrchestrator)
    response = client.post(f"/api/incidents/{INCIDENT_ID}/prevention/analyze")
    assert response.status_code == 200
    assert response.json()["execution_allowed"] is False
    assert response.json()["prevention_analysis"]["status"] == "COMPLETED"


def test_memory_endpoint(monkeypatch, tmp_path):
    import types

    from api import main

    memory_file = tmp_path / f"{INCIDENT_ID}.json"
    memory_file.write_text(
        f'{{"incident_id": "{INCIDENT_ID}", "incident_type": "SCHEMA_DRIFT"}}',
        encoding="utf-8",
    )
    fake_settings = types.SimpleNamespace(
        paths=types.SimpleNamespace(
            incidents_dir=main.settings.paths.incidents_dir,
            historical_dir=tmp_path,
        )
    )
    monkeypatch.setattr(main, "settings", fake_settings)
    monkeypatch.setattr(main, "find_similar_incidents", lambda incident_id: [])

    memory_response = client.get(f"/api/incidents/{INCIDENT_ID}/memory")
    assert memory_response.status_code == 200
    assert memory_response.json()["incident_id"] == INCIDENT_ID


def test_explanation_endpoint_is_advisory_only():
    """AI (if configured) may only narrate the decision - the endpoint must
    never expose approval/execution controls, and defaults to deterministic."""
    response = client.get(f"/api/incidents/{INCIDENT_ID}/explanation")
    assert response.status_code == 200

    body = response.json()
    assert body["source"] in ("deterministic", "llm")
    assert "REC-002" in body["narrative"]


def test_simulate_endpoint():
    response = client.post(f"/api/incidents/{INCIDENT_ID}/simulate")
    assert response.status_code == 200
    assert response.json()["simulation_count"] == 3


def test_simulate_unknown_incident_blocked():
    response = client.post("/api/incidents/INC-20990101-999/simulate")
    assert response.status_code == 404


def test_approval_already_approved_is_idempotent():
    response = client.post(
        f"/api/incidents/{INCIDENT_ID}/approval",
        json={"strategy_id": "REC-002", "decision": "APPROVE", "approver": "Someone Else"},
    )
    assert response.status_code == 200
    body = response.json()
    # Idempotent: the original approver/timestamp must not be overwritten.
    assert body["approved_by"] == "Rakesh Bontala"
    assert body["approval_status"] == "APPROVED"


def test_approval_rejects_wrong_strategy():
    response = client.post(
        f"/api/incidents/{INCIDENT_ID}/approval",
        json={"strategy_id": "REC-001", "decision": "APPROVE", "approver": "Someone"},
    )
    assert response.status_code == 409


def test_approval_rejects_malformed_strategy_id():
    response = client.post(
        f"/api/incidents/{INCIDENT_ID}/approval",
        json={"strategy_id": "bad-id", "decision": "APPROVE", "approver": "Someone"},
    )
    assert response.status_code == 400


def test_execute_already_executed_is_idempotent():
    response = client.post(f"/api/incidents/{INCIDENT_ID}/execute?strategy_id=REC-002")
    assert response.status_code == 200
    body = response.json()
    assert body["idempotent"] is True
    assert body["production_modified"] is False


def test_execute_unauthorized_strategy_is_blocked():
    response = client.post(f"/api/incidents/{INCIDENT_ID}/execute?strategy_id=REC-001")
    assert response.status_code == 409


def test_execute_malformed_strategy_id_rejected():
    response = client.post(f"/api/incidents/{INCIDENT_ID}/execute?strategy_id=not-valid")
    assert response.status_code == 400


def test_verify_endpoint():
    response = client.post(f"/api/incidents/{INCIDENT_ID}/verify")
    assert response.status_code == 200
    assert response.json()["verification_status"] == "PASSED"
