"""Recovery strategy risk evaluation.

Reads the recovery strategies generated by
`engine.recovery.recovery_engine` (single source of truth — no
duplicated strategy constants) and produces a weighted risk score per
strategy. Weights and classification thresholds are configurable via
`config.settings.RiskWeights` / environment variables.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from config.settings import settings
from engine.audit.audit_log import record_event
from engine.security.identifiers import validate_incident_id

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_INCIDENT_ID = "INC-20260930-001"

INCIDENTS_DIR = PROJECT_ROOT / "data" / "incidents"
STRATEGY_FILE = settings.paths.sandbox_recovery_dir / "strategies" / "recovery_strategies.json"
RISK_DIR = settings.paths.sandbox_recovery_dir / "risk"
RISK_FILE = RISK_DIR / "risk_evaluation.json"

# Deterministic severity points for the qualitative HIGH/MEDIUM/LOW levels
# used throughout the recovery strategy definitions.
SEVERITY_POINTS = {"HIGH": 3, "MEDIUM": 2, "LOW": 1}


def _severity_points(level: str) -> float:
    return SEVERITY_POINTS.get(level, SEVERITY_POINTS["MEDIUM"])


def _classify(risk_score: float) -> str:
    weights = settings.risk_weights
    if risk_score >= weights.blocked_risk_threshold:
        return "BLOCKED"
    if risk_score >= weights.high_risk_threshold:
        return "HIGH_RISK"
    if risk_score >= weights.medium_risk_threshold:
        return "MEDIUM_RISK"
    return "LOW_RISK"


def _numeric(value: float) -> float | int:
    """Render whole-number scores as int for a stable/familiar output shape."""
    return int(value) if float(value).is_integer() else round(value, 2)


def evaluate_risk(incident_id: str = DEFAULT_INCIDENT_ID) -> dict[str, Any]:
    validate_incident_id(incident_id)

    incident_file = INCIDENTS_DIR / f"{incident_id}.json"
    incident = json.loads(incident_file.read_text(encoding="utf-8"))

    if not STRATEGY_FILE.exists():
        raise FileNotFoundError(
            f"Recovery strategies not found: {STRATEGY_FILE}. "
            "Run engine.recovery.recovery_engine first."
        )

    strategy_data = json.loads(STRATEGY_FILE.read_text(encoding="utf-8"))

    if strategy_data.get("incident_id") != incident["incident_id"]:
        raise ValueError(
            "Recovery strategies file does not match the requested incident."
        )

    weights = settings.risk_weights
    evaluations = []

    for strategy in strategy_data["recovery_strategies"]:
        impact_scope = len(strategy.get("scope", []))

        execution_points = _severity_points(strategy["risk_level"]) * weights.execution
        runtime_points = _severity_points(strategy["runtime_class"]) * weights.runtime
        data_loss_points = _severity_points(strategy["data_loss_risk"]) * weights.data_loss
        impact_points = impact_scope * weights.impact_scope

        risk_score = execution_points + runtime_points + data_loss_points + impact_points

        evaluations.append(
            {
                "strategy_id": strategy["strategy_id"],
                "name": strategy["name"],
                "risk_score": _numeric(risk_score),
                "risk_classification": _classify(risk_score),
                "risk_factors": {
                    "execution_risk": strategy["risk_level"],
                    "runtime_risk": strategy["runtime_class"],
                    "data_loss_risk": strategy["data_loss_risk"],
                    "impact_scope": impact_scope,
                },
                "risk_weight_breakdown": {
                    "execution_points": _numeric(execution_points),
                    "runtime_points": _numeric(runtime_points),
                    "data_loss_points": _numeric(data_loss_points),
                    "impact_points": _numeric(impact_points),
                },
                "human_approval_required": True,
            }
        )

    result = {
        "incident_id": incident["incident_id"],
        "evaluated_strategy_count": len(evaluations),
        "risk_weights_applied": {
            "execution": weights.execution,
            "runtime": weights.runtime,
            "data_loss": weights.data_loss,
            "impact_scope": weights.impact_scope,
        },
        "risk_evaluations": evaluations,
    }

    RISK_DIR.mkdir(parents=True, exist_ok=True)
    RISK_FILE.write_text(json.dumps(result, indent=2), encoding="utf-8")

    record_event(
        incident_id=incident["incident_id"],
        action="risk_evaluated",
        status="PASSED",
        details={"evaluated_strategy_count": len(evaluations)},
    )

    return result


def main() -> None:
    result = evaluate_risk()

    print("Recovery Risk Evaluation:")
    print(json.dumps(result, indent=2))
    print(f"Risk evaluation written to: {RISK_FILE}")
    print("RISK EVALUATION PASSED")


if __name__ == "__main__":
    main()